name: Linux CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare environment
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install build-essential
        sudo apt install libx11-dev libxcursor-dev libxrandr-dev libxi-dev libxinerama-dev libgcrypt-dev libgl1-mesa-dev
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -S .. -B .
        make
    - name: Archive executable
      uses: actions/upload-artifact@v2
      with:
        name: itsraining
        path: |
          build
          build/itsraining
          ./fonts
