name: MSYS2
on: [push, pull_request]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc 
      - name: CI-Build
        run: |
          pacman --noconfirm -S mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-libgcrypt mingw-w64-ucrt-x86_64-make
          mkdir build
          cd build
          /mingw32/bin/cmake -G "MinGW Makefiles" -S .. -B .
          make
