name: MSYS2
on: [push, pull_request]

jobs:
  mingw64-gcc:
    name: MinGW GCC

    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: "Configuration"
        run: |
          git clone https://github.com/Chronic-Dev/libgcrypt.git
          git clone https://github.com/Chronic-Dev/libgpg-error.git
          cd libgpg-error
          ./autogen.sh --build-w32
          make
          make install
          cd ../libgcrypt
          ./autogen.sh --build-w32
          make
          make install
          cd ..
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -S .. -B .
          pwd
          ls -la
          make
      - name: Archive executable
        uses: actions/upload-artifact@v2
        with:
          name: itsraining
          path: |
            build

