name: MSYS2
on: [push, pull_request]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-libgcrypt mingw-w64-ucrt-x86_64-gcc mingw-w64-x86_64-binutils mingw-w64-x86_64-make make mingw-w64-x86_64-cmake cmake
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          mkdir build
          cd build
          cmake -S .. -B .
          make
      - name: Copy libraries
        run: |
          cp /usr/bin/msys-gcrypt-20.dll bin/libgcrypt-20.dll
          cp /usr/bin/msys-2.0.dll bin/
          cp /usr/bin/msys-gpg-error-0.dll bin/
          cp /usr/bin/msys-iconv-2.dll bin/
          cp /usr/bin/msys-intl-8.dll bin/
      - name: Archive executable
        uses: actions/upload-artifact@v2
        with:
          name: itsraining
          path: |
            build
