name: MSYS2
on: [push, pull_request]

jobs:
  mingw64-gcc:
    name: MinGW GCC

    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: "Setup"
        run: |
          mkdir build
          cd build
          cmake -S .. -B .

