name: MSYS2
on: [push, pull_request]

jobs:
  mingw64-gcc:
    name: MinGW GCC

    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: "Configuration"
        run: |
          mkdir build
          cd build
          cmake -S .. -B .
      - name: "Build"
        run: |
          cd build
          make
      - name: Archive executable
        uses: actions/upload-artifact@v2
        with:
          name: itsraining
          path: |
            build

