name: Mingw
on: [push, pull_request]

jobs:
  mingw64-gcc:
    name: MinGW GCC

    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: "Setup"
        run: |
          gcc --version
          cmake --version

